remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: Public Facing Data
description: Personal dataset I am willing to expose to the world.

# google_analytics: [Your Google Analytics tracking ID]
